# Generated by Django 5.0.3 on 2024-03-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rol_usuario_auth_token_usuario_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='path',
            field=models.CharField(default='index.html', max_length=30),
        ),
    ]
