# Generated by Django 5.0.3 on 2024-03-11 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rol_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=30)),
                ('att', models.BooleanField(default=False)),
                ('recog', models.CharField(max_length=30)),
                ('doc', models.CharField(max_length=60)),
                ('uname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.rol')),
            ],
        ),
    ]
